<a href="https://colab.research.google.com/github/alexandergribenchenko/Data_Science_Finanzas/blob/main/Binance_P2P.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
import pandas as pd
from datetime import datetime

In [5]:
import requests
import pandas as pd

def obtener_anuncios_p2p(fiat="COP", asset="USDT", trade_type="BUY", pagina=1, filas=20):
    """
    Consulta el endpoint público que usa la web de Binance P2P
    para listar anuncios de compra/venta.

    Parametros:
        fiat: moneda fiat, ej. "COP", "VES", "ARS", "MXN"
        asset: criptomoneda, ej. "USDT", "BTC"
        trade_type: "BUY" o "SELL" (desde la perspectiva del que consulta)
        pagina: numero de pagina de resultados
        filas: cantidad de anuncios por pagina (max 20 recomendado)
    """
    url = "https://p2p.binance.com/bapi/c2c/v2/friendly/c2c/adv/search"

    payload = {
        "fiat": fiat,
        "page": pagina,
        "rows": filas,
        "tradeType": trade_type,
        "asset": asset,
        "countries": [],
        "proMerchantAds": False,
        "shieldMerchantAds": False,
        "publisherType": None,
        "payTypes": [],
        "classifies": ["mass", "profession", "fiat_trade"]
    }

    headers = {
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    }

    respuesta = requests.post(url, json=payload, headers=headers, timeout=10)
    respuesta.raise_for_status()
    datos = respuesta.json()

    anuncios = datos.get("data", [])
    filas_tabla = []

    for anuncio in anuncios:
        adv = anuncio.get("adv", {})
        advertiser = anuncio.get("advertiser", {})
        metodos_pago = [m.get("tradeMethodName") for m in adv.get("tradeMethods", [])]

        filas_tabla.append({
            "comerciante": advertiser.get("nickName"),
            "precio": float(adv.get("price", 0)),
            "moneda": fiat,
            "disponible": float(adv.get("surplusAmount", 0)),
            "limite_min": float(adv.get("minSingleTransAmount", 0)),
            "limite_max": float(adv.get("dynamicMaxSingleTransAmount", 0)),
            "metodos_pago": ", ".join(metodos_pago),
            "ordenes_completadas": advertiser.get("monthOrderCount"),
            "tasa_finalizacion_%": round(float(advertiser.get("monthFinishRate", 0)) * 100, 2),
            "insignia_verificado": advertiser.get("userType"),
            "tiempo_respuesta_min": adv.get("payTimeLimit", 0) // 60 if adv.get("payTimeLimit") else None,
        })

    return pd.DataFrame(filas_tabla)


# Llamada y visualización directa del DataFrame
df_vendedores = obtener_anuncios_p2p(fiat="COP", asset="USDT", trade_type="BUY", filas=20)
df_vendedores

,comerciante,precio,moneda,disponible,limite_min,limite_max,metodos_pago,ordenes_completadas,tasa_finalizacion_%,insignia_verificado,tiempo_respuesta_min
0,JimenaR-Coins,3499.35,COP,40052.49,40000.0,25000000.0,"Bancolombia S.A, Nequi, Bre-B Keys",7991,99.9,merchant,0
1,Cambios_Avg,3329.90,COP,149.67,300000.0,497143.0,Bancolombia S.A,141,96.6,user,0
2,Jada_store,3330.00,COP,300.00,100000.0,996508.0,Bancolombia S.A,137,93.9,user,0
3,CF2-Exchanges,3330.00,COP,1000.00,3000000.0,3000001.0,"Bancolombia S.A, Nequi",2169,99.6,merchant,0
4,GlobalTraderVA,3331.99,COP,1535.00,500000.0,4000000.0,Bancolombia S.A,17,100.0,user,0
5,cripto86,3332.00,COP,36.44,100000.0,121115.0,Bancolombia S.A,91,96.9,user,0
6,MoneyExpress1,3332.00,COP,500.00,500000.0,1661845.0,Bancolombia S.A,568,96.5,user,0
7,PAGO-EXPREXX,3334.79,COP,186.74,596000.0,621650.0,Bancolombia S.A,2698,100.0,merchant,0
8,User-j6598,3335.00,COP,10000.00,15000000.0,25000000.0,"Bancolombia S.A, Bre-B Keys",70,100.0,user,0
9,Yorbe_Studio,3335.00,COP,840.57,1000000.0,2796310.0,Bancolombia S.A,162,95.9,user,0
10,capiramirez,3335.00,COP,194.20,630000.0,640000.0,"Bancolombia S.A, Nequi",12,100.0,user,0
11,CryptoBarpi,3335.00,COP,2157.80,1000000.0,7178317.0,"Bancolombia S.A, Bre-B Keys, BBVA, Nequi, Davi...",60,100.0,user,1
12,Kadaki_fast,3335.00,COP,10020.00,10999312.0,11000000.0,Bancolombia S.A,95,84.1,merchant,0
13,sheva07,3335.00,COP,144.26,250000.0,480146.0,Nequi,1005,100.0,merchant,0
14,TradeUSDTExpress,3338.00,COP,2052.39,1500000.0,6838909.0,"Nequi, Bre-B Keys",21498,100.0,merchant,0
15,MULTICAMBIOS2020,3339.00,COP,800.00,2450000.0,2450001.0,"Bancolombia S.A, Nequi",1105,99.4,merchant,0
16,DERPS,3339.90,COP,472.02,1567000.0,1572568.0,Bancolombia S.A,5,100.0,user,0
17,CENTROPAGOS1,3339.95,COP,5011.80,3000000.0,16697417.0,Bancolombia S.A,129,100.0,user,0
18,CRYPTO-RUEDA-EXPRES,3340.00,COP,29.89,40000.0,99583.0,Nequi,374,99.8,user,0
19,NMR Digital Assets,3340.00,COP,705.27,800000.0,2350899.0,"Nequi, BBVA, Davivienda S.A, Bancolombia S.A, ...",1157,98.8,merchant,0
20,BAYONEX-p2p,3340.00,COP,865.50,33600.0,350000.0,"Daviplata, Davivienda S.A, Nequi, Banco Caja S...",65,94.3,user,0

In [7]:
import requests
import pandas as pd

def obtener_anuncios_p2p(fiat="COP", asset="USDT", trade_type="BUY", pagina=1, filas=20):
    url = "https://p2p.binance.com/bapi/c2c/v2/friendly/c2c/adv/search"

    payload = {
        "fiat": fiat,
        "page": pagina,
        "rows": filas,
        "tradeType": trade_type,
        "asset": asset,
        "countries": [],
        "proMerchantAds": False,
        "shieldMerchantAds": False,
        "publisherType": None,
        "payTypes": [],
        "classifies": ["mass", "profession", "fiat_trade"]
    }

    headers = {
        "Content-Type": "application/json",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    }

    respuesta = requests.post(url, json=payload, headers=headers, timeout=10)
    respuesta.raise_for_status()
    datos = respuesta.json()

    anuncios = datos.get("data", [])
    filas_tabla = []

    for anuncio in anuncios:
        adv = anuncio.get("adv", {})
        advertiser = anuncio.get("advertiser", {})
        metodos_pago = [m.get("tradeMethodName") for m in adv.get("tradeMethods", [])]

        filas_tabla.append({
            "codigo_vendedor": advertiser.get("userNo"),   # <-- el advertiserNo de la URL
            "comerciante": advertiser.get("nickName"),
            "precio": float(adv.get("price", 0)),
            "moneda": fiat,
            "disponible": float(adv.get("surplusAmount", 0)),
            "limite_min": float(adv.get("minSingleTransAmount", 0)),
            "limite_max": float(adv.get("dynamicMaxSingleTransAmount", 0)),
            "metodos_pago": ", ".join(metodos_pago),
            "ordenes_completadas": advertiser.get("monthOrderCount"),
            "tasa_finalizacion_%": round(float(advertiser.get("monthFinishRate", 0)) * 100, 2),
            "insignia_verificado": advertiser.get("userType"),
            "tiempo_respuesta_min": adv.get("payTimeLimit", 0) // 60 if adv.get("payTimeLimit") else None,
        })

    return pd.DataFrame(filas_tabla)


df_vendedores = obtener_anuncios_p2p(fiat="COP", asset="USDT", trade_type="BUY", filas=20)
df_vendedores

,codigo_vendedor,comerciante,precio,moneda,disponible,limite_min,limite_max,metodos_pago,ordenes_completadas,tasa_finalizacion_%,insignia_verificado,tiempo_respuesta_min
0,sa19c588fa9a730f8a717a82950138f76,JimenaR-Coins,3499.35,COP,38755.22,40000.0,25000000.0,"Bancolombia S.A, Nequi, Bre-B Keys",7998,99.9,merchant,0
1,s427c4cfcdd8139008b7c22e159fec82c,Jada_store,3330.00,COP,88.23,100000.0,293073.0,Bancolombia S.A,137,93.9,user,0
2,s22b52acaaf7239eba8b4e4976f0bcd48,inversiones_10,3330.00,COP,448.26,200000.0,1488983.0,"Bancolombia S.A, Bre-B Keys",75,100.0,user,0
3,sa9af913c06d63db793b71653c065d2a7,Kadaki_fast,3330.00,COP,10020.00,10999312.0,11000000.0,Bancolombia S.A,95,84.1,merchant,0
4,s60b30e33ad7e3e519f852c0476dd6dc3,cripto86,3332.00,COP,36.44,100000.0,121115.0,Bancolombia S.A,91,96.9,user,0
5,s7d844fbde00837f390d5ce5a9cbf3848,PAGO-EXPREXX,3334.79,COP,125.31,416000.0,417152.0,Bancolombia S.A,2699,100.0,merchant,0
6,s6a69305bd21936aab730876bd12e2829,Fast Cash,3334.98,COP,240.50,800000.0,800461.0,"Bancolombia S.A, Bre-B Keys",164,94.3,merchant,0
7,sd56376eac3913755bee8ac348b5c4b94,User-j6598,3335.00,COP,10000.00,15000000.0,25000000.0,"Bancolombia S.A, Bre-B Keys",70,100.0,user,0
8,sb8e5bb52d8543319a18fe6d36d80945e,Yorbe_Studio,3335.00,COP,840.57,1000000.0,2796310.0,Bancolombia S.A,162,95.9,user,0
9,s2b8615acdb9b335790d526be3b558721,capiramirez,3335.00,COP,194.20,630000.0,640000.0,"Bancolombia S.A, Nequi",12,100.0,user,0
10,sb5034286ad3836dab4638da749507ceb,CryptoBarpi,3335.00,COP,1677.07,1000000.0,5579080.0,"Bancolombia S.A, Bre-B Keys, BBVA, Nequi, Davi...",60,100.0,user,1
11,sf8bbede211f631c1aa28e92c40d1653d,lafortaleza07,3337.00,COP,700.00,2199999.0,2200000.0,Bancolombia S.A,590,99.4,merchant,0
12,s67bff11beb7131b2a6921aa22d653833,ZYNKROTECH_CO,3338.95,COP,900.00,130000.0,390000.0,"Davivienda S.A, Bre-B Keys",115,100.0,user,0
13,s915047a7556439c197b0f3ae021fc47a,MULTICAMBIOS2020,3339.00,COP,150.00,439000.0,439001.0,"Bancolombia S.A, Nequi",1105,99.4,merchant,0
14,scd4b4d0c48133ab987162200dee92892,DERPS,3339.90,COP,472.02,1567000.0,1572568.0,Bancolombia S.A,5,100.0,user,0
15,s76cdfb33f5f731faaa4fa81e3d5f9f2f,CENTROPAGOS1,3339.95,COP,5011.80,3000000.0,16697417.0,Bancolombia S.A,129,100.0,user,0
16,s614c753e5a3d35c59cfb2ad05b3c8996,waves97,3340.00,COP,500.00,1600000.0,1665835.0,Bancolombia S.A,0,0.0,user,0
17,s64b5365d4c213ffbac6cec676e892a80,Inversiones_MQ,3340.00,COP,219.62,50000.0,731701.0,"Bancolombia S.A, Bre-B Keys",847,99.3,user,0
18,s5983bbcdd084347980a2e4729af1c251,CRIPTOHEAVEN,3340.25,COP,67.13,200000.0,223671.0,Bre-B Keys,236,93.7,user,0
19,sbb5314bf7508397180e993cf4b532cfe,INITIUM_CO,3341.93,COP,4002.17,300000.0,3000000.0,"Bancolombia S.A, Nequi, Bre-B Keys, Davivienda...",60045,99.7,merchant,0
20,s8a2b7011c94a31feb7af0956075d1791,Mega_Corporation,3341.94,COP,762.40,2500000.0,2543444.0,Nequi,1680,99.8,merchant,0

In [6]:
import requests
import pandas as pd
import re
import json

def obtener_perfil_vendedor(advertiser_no):
    """
    Extrae la informacion del perfil de un vendedor P2P de Binance
    a partir de su pagina publica de detalle.
    """
    url = f"https://c2c.binance.com/en/advertiserDetail?advertiserNo={advertiser_no}"
    headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"}

    respuesta = requests.get(url, headers=headers, timeout=10)
    respuesta.raise_for_status()
    html = respuesta.text

    match = re.search(
        r'<script id="__NEXT_DATA__" type="application/json">(.*?)</script>',
        html, re.DOTALL
    )
    if not match:
        raise ValueError("No se encontro __NEXT_DATA__. Puede necesitar Selenium/Playwright.")

    return json.loads(match.group(1))


# Paso 1: correlo así primero para ver la estructura real
advertiser_no = "sa19c588fa9a730f8a717a82950138f76"
datos = obtener_perfil_vendedor(advertiser_no)

# Esto te va a mostrar cómo está organizado el JSON por dentro
print(list(datos["props"]["pageProps"].keys()))

ValueError: No se encontro __NEXT_DATA__. Puede necesitar Selenium/Playwright.