<a href="https://colab.research.google.com/github/alexandergribenchenko/Data_Science_Finanzas/blob/main/NB_01_Creditos_Graficos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# A. Librerías

In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
# pd.set_option('display.float_format', '{:,.2f}'.format)

# B. Funciones propias

In [2]:
def tabla_mensual_amortizacion_francesa(
    capital_inicial,
    tasa,
    periodos_n,
    periodos_temporalidad='mensual',
    tasa_temporalidad='mensual',
    tasa_tipo='nominal',
    m=12
):
    # convertir número de periodos a meses si está en años
    if periodos_temporalidad == 'mensual':
        n = periodos_n
    elif periodos_temporalidad == 'anual':
        n = periodos_n * m
    else:
        raise ValueError("periodos_temporalidad debe ser 'mensual' o 'anual'")

    # convertir tasa a tasa mensual nominal
    if tasa_temporalidad == 'mensual':
        tasa_periodo = tasa
    elif tasa_temporalidad == 'anual':
        if tasa_tipo == 'efectiva':
            tasa_periodo = (1 + tasa) ** (1 / m) - 1
        elif tasa_tipo == 'nominal':
            tasa_periodo = tasa / m
        else:
            raise ValueError("tasa_tipo debe ser 'nominal' o 'efectiva'")
    else:
        raise ValueError("tasa_temporalidad debe ser 'mensual' o 'anual'")

    # cuota fija sistema francés
    cuota = capital_inicial * (tasa_periodo * (1 + tasa_periodo) ** n) / ((1 + tasa_periodo) ** n - 1)

    df = pd.DataFrame({'periodo': range(0, n + 1)})

    saldo_insoluto = lambda k: capital_inicial * ((1 + tasa_periodo) ** n - (1 + tasa_periodo) ** k) / ((1 + tasa_periodo) ** n - 1)
    saldo_inicial = lambda k: capital_inicial if k == 1 else saldo_insoluto(k - 1)
    interes_k = lambda k: saldo_inicial(k) * tasa_periodo if k >= 1 else 0
    amortizacion_k = lambda k: cuota - interes_k(k) if k >= 1 else 0

    df['amortizacion'] = df['periodo'].apply(lambda k: round(amortizacion_k(k), 2))
    df['interes'] = df['periodo'].apply(lambda k: round(interes_k(k), 2))
    df['pago_mensual'] = df['periodo'].apply(lambda k: 0 if k == 0 else round(cuota, 2))
    df['saldo'] = df['periodo'].apply(lambda k: round(saldo_insoluto(k), 2))

    print('x = 2', float(df.amortizacion.sum()))

    return df

# 01. Prestamo original

In [25]:
df = tabla_mensual_amortizacion_francesa(
    capital_inicial=90_000_000,
    tasa=0.08688,
    periodos_n = 84,
    periodos_temporalidad = 'mensual',
    tasa_temporalidad='anual',
    tasa_tipo='efectiva'
)

fecha_inicio = '2021-01-01'

# Crear rango de fechas mensuales
fechas = pd.date_range(start=fecha_inicio, periods=len(df), freq='MS')  # 'MS' = Month Start

# Crear nueva columna con formato 'YYYY-MM'
df['periodo'] = fechas.strftime('%Y-%m')
df

x = 2 90000000.0

    periodo  amortizacion    interes  pago_mensual        saldo
0   2021-01          0.00       0.00          0.00  90000000.00
1   2021-02     791952.54  627008.06    1418960.61  89208047.46
2   2021-03     797469.88  621490.72    1418960.61  88410577.57
3   2021-04     803025.66  615934.94    1418960.61  87607551.91
4   2021-05     808620.15  610340.46    1418960.61  86798931.76
5   2021-06     814253.61  604707.00    1418960.61  85984678.16
6   2021-07     819926.31  599034.29    1418960.61  85164751.85
7   2021-08     825638.54  593322.07    1418960.61  84339113.31
8   2021-09     831390.56  587570.05    1418960.61  83507722.75
9   2021-10     837182.66  581777.95    1418960.61  82670540.09
10  2021-11     843015.10  575945.50    1418960.61  81827524.98
11  2021-12     848888.19  570072.42    1418960.61  80978636.80
12  2022-01     854802.18  564158.42    1418960.61  80123834.62
13  2022-02     860757.38  558203.23    1418960.61  79263077.24
14  2022-03     866754.07  552206.54    1418960.61  78396323.17
15  2022-04     872792.53  546168.08    1418960.61  77523530.64
16  2022-05     878873.06  540087.54    1418960.61  76644657.57
17  2022-06     884995.96  533964.65    1418960.61  75759661.61
18  2022-07     891161.51  527799.10    1418960.61  74868500.10
19  2022-08     897370.02  521590.59    1418960.61  73971130.09
20  2022-09     903621.77  515338.83    1418960.61  73067508.31
21  2022-10     909917.09  509043.52    1418960.61  72157591.23
22  2022-11     916256.26  502704.35    1418960.61  71241334.97
23  2022-12     922639.59  496321.02    1418960.61  70318695.38
24  2023-01     929067.40  489893.21    1418960.61  69389627.99
25  2023-02     935539.98  483420.63    1418960.61  68454088.00
26  2023-03     942057.66  476902.95    1418960.61  67512030.34
27  2023-04     948620.75  470339.86    1418960.61  66563409.60
28  2023-05     955229.56  463731.05    1418960.61  65608180.04
29  2023-06     961884.41  457076.20    1418960.61  64646295.63
30  2023-07     968585.62  450374.98    1418960.61  63677710.01
31  2023-08     975333.52  443627.08    1418960.61  62702376.49
32  2023-09     982128.43  436832.17    1418960.61  61720248.05
33  2023-10     988970.68  429989.92    1418960.61  60731277.37
34  2023-11     995860.60  423100.01    1418960.61  59735416.77
35  2023-12    1002798.52  416162.09    1418960.61  58732618.25
36  2024-01    1009784.77  409175.84    1418960.61  57722833.48
37  2024-02    1016819.70  402140.91    1418960.61  56706013.79
38  2024-03    1023903.63  395056.98    1418960.61  55682110.16
39  2024-04    1031036.92  387923.69    1418960.61  54651073.24
40  2024-05    1038219.90  380740.71    1418960.61  53612853.34
41  2024-06    1045452.93  373507.68    1418960.61  52567400.41
42  2024-07    1052736.34  366224.27    1418960.61  51514664.07
43  2024-08    1060070.50  358890.11    1418960.61  50454593.57
44  2024-09    1067455.75  351504.86    1418960.61  49387137.82
45  2024-10    1074892.46  344068.15    1418960.61  48312245.37
46  2024-11    1082380.97  336579.64    1418960.61  47229864.40
47  2024-12    1089921.65  329038.95    1418960.61  46139942.74
48  2025-01    1097514.87  321445.73    1418960.61  45042427.87
49  2025-02    1105160.99  313799.62    1418960.61  43937266.88
50  2025-03    1112860.38  306100.23    1418960.61  42824406.50
51  2025-04    1120613.40  298347.20    1418960.61  41703793.10
52  2025-05    1128420.45  290540.16    1418960.61  40575372.65
53  2025-06    1136281.88  282678.73    1418960.61  39439090.78
54  2025-07    1144198.07  274762.53    1418960.61  38294892.70
55  2025-08    1152169.42  266791.18    1418960.61  37142723.28
56  2025-09    1160196.31  258764.30    1418960.61  35982526.97
57  2025-10    1168279.11  250681.49    1418960.61  34814247.86
58  2025-11    1176418.23  242542.38    1418960.61  33637829.63
59  2025-12    1184614.05  234346.56    1418960.61  32453215.59
60  2026-01    1192866.96  226093.64    1418960.61  31260348.62
61  2026-02    1201177.38  217783.23    1418960.61  30059171.24
62  2026-03    1209545.69  209414.92    1418960.61  28849625.56
63  2026-04    1217972.30  200988.31    1418960.61  27631653.26
64  2026-05    1226457.61  192502.99    1418960.61  26405195.65
65  2026-06    1235002.04  183958.56    1418960.61  25170193.60
66  2026-07    1243606.00  175354.60    1418960.61  23926587.60
67  2026-08    1252269.90  166690.70    1418960.61  22674317.69
68  2026-09    1260994.16  157966.44    1418960.61  21413323.53
69  2026-10    1269779.20  149181.41    1418960.61  20143544.33
70  2026-11    1278625.44  140335.16    1418960.61  18864918.89
71  2026-12    1287533.32  131427.29    1418960.61  17577385.57
72  2027-01    1296503.25  122457.36    1418960.61  16280882.33
73  2027-02    1305535.67  113424.94    1418960.61  14975346.66
74  2027-03    1314631.02  104329.59    1418960.61  13660715.64
75  2027-04    1323789.73   95170.88    1418960.61  12336925.91
76  2027-05    1333012.25   85948.36    1418960.61  11003913.66
77  2027-06    1342299.02   76661.58    1418960.61   9661614.64
78  2027-07    1351650.49   67310.11    1418960.61   8309964.14
79  2027-08    1361067.11   57893.49    1418960.61   6948897.03
80  2027-09    1370549.33   48411.27    1418960.61   5578347.70
81  2027-10    1380097.62   38862.99    1418960.61   4198250.08
82  2027-11    1389712.42   29248.19    1418960.61   2808537.66
83  2027-12    1399394.21   19566.40    1418960.61   1409143.45
84  2028-01    1409143.45    9817.16    1418960.61         0.00

In [33]:
df['interes_acomulado'] = df['interes'].cumsum()
df['interes_total'] = df['interes'].sum()

df['amortizacion_acomulada'] = df['amortizacion'].cumsum()
df['amortizacion_total'] = df['amortizacion'].sum()

df['pago_mensual_acomulado'] = df['pago_mensual'].cumsum()
df['pago_total_prestamo'] = df['pago_mensual'].sum()

# df['pct_interes_pago_mensual'] =  round(df['interes']/df['pago_mensual'],2)
# df['pct_amortizacion_pago_mensual'] =  round(df['amortizacion']/df['pago_mensual'],2)

# df['pct_interes_interes_total'] =  round(df['interes']/df['interes_total'],2)
# df['pct_interes_acomulado_interes_total'] =  round(df['interes_acomulado']/df['interes_total'],4)

df['pct_interes_pago_mensual'] = df['interes'] / df['pago_mensual']
df['pct_amortizacion_pago_mensual'] = df['amortizacion'] / df['pago_mensual']
df['pct_interes_interes_total'] = df['interes'] / df['interes_total']
df['pct_interes_acomulado_interes_total'] = df['interes_acomulado'] / df['interes_total']

# Normalizar acumulados a porcentaje de su total final (para que terminen en 100)
df["pct_amortizacion"] = df["amortizacion_acomulada"] / df["amortizacion_total"] * 100
df["pct_interes"] = df["interes_acomulado"] / df["interes_total"] * 100
df["pct_pago"] = df["pago_mensual_acomulado"] / df["pago_total_prestamo"] * 100

columns_interest = ['periodo',
                    'pago_mensual', 'pago_mensual_acomulado', 'pago_total_prestamo',
                    'amortizacion', 'amortizacion_acomulada','amortizacion_total',
                    'interes', 'interes_acomulado','interes_total',
                    'pct_interes_pago_mensual', 'pct_amortizacion_pago_mensual',
                    'pct_interes_interes_total', 'pct_interes_acomulado_interes_total']
df = df[columns_interest].reset_index(drop=False).rename(columns={'index':'cuota'})
df['periodo'] = pd.to_datetime(df['periodo'])

money_cols = [
    "pago_mensual", "pago_mensual_acomulado", "pago_total_prestamo",
    "amortizacion", "amortizacion_acomulada", "amortizacion_total",
    "interes", "interes_acomulado", "interes_total"
]

rate_cols = [
    "pct_interes_pago_mensual",
    "pct_amortizacion_pago_mensual",
    "pct_interes_interes_total",
    "pct_interes_acomulado_interes_total"
]

money_fmt = "{:,.2f}"
rate_fmt = "{:,.4f}"

fmt_dict = {col: money_fmt for col in money_cols} | {col: rate_fmt for col in rate_cols}

df.style.format(fmt_dict)

In [34]:
import plotly.graph_objects as go
df_plot = df.copy()

# Creamos un hovertext global con Fecha + Cuota
fig = go.Figure()

# Definimos la cabecera única con fecha y cuota
custom_header = (
    "Periodo: %{x|%Y-%m}<br>" +  # Fecha en formato Año-Mes
    "Cuota: %{customdata}<br>"
)

# % Capital
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_amortizacion"],
    mode="lines+markers",
    name="% Capital acumulado",
    customdata=df_plot["cuota"],  # pasamos la cuota
    hovertemplate=custom_header + "%{y:.2f}%<extra></extra>",
    line=dict(color="seagreen")
))

# % Intereses
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_interes"],
    mode="lines+markers",
    name="% Interés acumulado",
    customdata=df_plot["cuota"],
    hovertemplate=custom_header + "%{y:.2f}%<extra></extra>",
    line=dict(color="tomato")
))

# % Pago total
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_pago"],
    mode="lines+markers",
    name="% Pago total acumulado",
    customdata=df_plot["cuota"],
    hovertemplate=custom_header + "%{y:.2f}%<extra></extra>",
    line=dict(color="royalblue")
))

# Layout
fig.update_layout(
    title="% de avance relativo de cada componente (cada uno normalizado a 100%)",
    xaxis=dict(title="Periodo", tickformat="%Y-%m"),
    yaxis=dict(title="Porcentaje acumulado (%)", range=[0, 105], showgrid=True),
    hovermode="x unified",
    hoverlabel=dict(bgcolor="white", font_size=12),
    legend=dict(x=0.01, y=0.99, bgcolor="rgba(255,255,255,0.8)")
)

fig.show()

KeyError: 'pct_amortizacion'

In [17]:
import plotly.graph_objects as go

# Creamos un hovertext global con Fecha + Cuota
df_plot["hover_info"] = (
    "Periodo: " + df_plot["periodo"].astype(str) +
    "<br>Cuota: " + df_plot["cuota"].astype(str)
)

fig = go.Figure()

# % Capital
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_amortizacion"],
    mode="lines+markers",
    name="% Capital acumulado",
    hovertemplate="%{y:.2f}%<extra></extra>",
    line=dict(color="seagreen")
))

# % Intereses
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_interes"],
    mode="lines+markers",
    name="% Interés acumulado",
    hovertemplate="%{y:.2f}%<extra></extra>",
    line=dict(color="tomato")
))

# % Pago total
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_pago"],
    mode="lines+markers",
    name="% Pago total acumulado",
    hovertemplate="%{y:.2f}%<extra></extra>",
    line=dict(color="royalblue")
))

# Layout con hover unificado
fig.update_layout(
    title="% de avance relativo de cada componente (cada uno normalizado a 100%)",
    xaxis=dict(title="Periodo", tickformat="%Y-%m"),
    yaxis=dict(title="Porcentaje acumulado (%)", range=[0, 105], showgrid=True),
    hovermode="x unified",
    hoverlabel=dict(bgcolor="white", font_size=12),
    legend=dict(x=0.01, y=0.99, bgcolor="rgba(255,255,255,0.8)")
)

# Truco: mostrar solo una vez la info general (fecha + cuota)
fig.update_layout(
    hovermode="x unified",
    hoverlabel=dict(namelength=0)
)
fig.update_traces(hoverinfo="text+name")

# Inyectamos el texto global en cada punto, pero aparecerá solo una vez en el encabezado
for trace in fig.data:
    trace.text = df_plot["hover_info"]

fig.show()

In [16]:
fig = go.Figure()

# % Capital
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_amortizacion"],
    mode="lines+markers",
    name="% Capital acumulado",
    customdata=df_plot["cuota"],
    hovertemplate="%{y:.2f}%<extra></extra>",  # solo valor
    line=dict(color="seagreen")
))

# % Intereses
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_interes"],
    mode="lines+markers",
    name="% Interés acumulado",
    customdata=df_plot["cuota"],
    hovertemplate="%{y:.2f}%<extra></extra>",  # solo valor
    line=dict(color="tomato")
))

# % Pago total
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_pago"],
    mode="lines+markers",
    name="% Pago total acumulado",
    customdata=df_plot["cuota"],
    hovertemplate="%{y:.2f}%<extra></extra>",  # solo valor
    line=dict(color="royalblue")
))

# Layout con hover unificado
fig.update_layout(
    title="% de avance relativo de cada componente (cada uno normalizado a 100%)",
    xaxis=dict(title="Periodo"),
    yaxis=dict(
        title="Porcentaje acumulado (%)",
        range=[0, 105],
        showgrid=True,
        zeroline=False
    ),
    hovermode="x unified",
    legend=dict(x=0.01, y=0.99, bgcolor="rgba(255,255,255,0.8)")
)

# Personalizar cabecera del hover unificado (fecha + cuota)
fig.update_traces(customdata=df_plot["cuota"])
fig.update_layout(
    hoverlabel=dict(bgcolor="white", font_size=12),
    xaxis=dict(
        tickformat="%Y-%m",
        title="Periodo"
    )
)

fig.show()

In [15]:
import plotly.graph_objects as go

# Filtrar desde la cuota 1 en adelante
df_plot = df.iloc[1:].copy()

# Totales finales
total_amortizacion = df["amortizacion_acomulada"].iloc[-1]
total_interes = df["interes_acomulado"].iloc[-1]
total_pago = df["pago_mensual_acomulado"].iloc[-1]

# Normalización
df_plot["pct_amortizacion"] = df_plot["amortizacion_acomulada"] / total_amortizacion * 100
df_plot["pct_interes"] = df_plot["interes_acomulado"] / total_interes * 100
df_plot["pct_pago"] = df_plot["pago_mensual_acomulado"] / total_pago * 100

fig = go.Figure()

# % Capital
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_amortizacion"],
    mode="lines+markers",
    name="% Capital acumulado",
    customdata=df_plot["cuota"],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "% Capital acumulado: %{y:.2f}%<extra></extra>",
    line=dict(color="seagreen")
))

# % Intereses
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_interes"],
    mode="lines+markers",
    name="% Interés acumulado",
    customdata=df_plot["cuota"],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "% Interés acumulado: %{y:.2f}%<extra></extra>",
    line=dict(color="tomato")
))

# % Pago total
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_pago"],
    mode="lines+markers",
    name="% Pago total acumulado",
    customdata=df_plot["cuota"],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "% Pago acumulado: %{y:.2f}%<extra></extra>",
    line=dict(color="royalblue")
))

# Layout
fig.update_layout(
    title="% de avance relativo de cada componente (cada uno normalizado a 100%)",
    xaxis=dict(title="Periodo"),
    yaxis=dict(
        title="Porcentaje acumulado (%)",
        range=[0, 105],
        showgrid=True,
        zeroline=False
    ),
    hovermode="x unified",
    legend=dict(x=0.01, y=0.99, bgcolor="rgba(255,255,255,0.8)")
)

fig.show()

In [14]:
import plotly.graph_objects as go

# Filtrar desde la cuota 1 en adelante (omitimos la inicial con 0s)
df_plot = df.iloc[1:].copy()

# Normalización contra el total pagado al final
total_pagado = df["pago_total_prestamo"].iloc[0]

df_plot["pct_amortizacion_total_pago"] = df_plot["amortizacion_acomulada"] / total_pagado * 100
df_plot["pct_interes_total_pago"] = df_plot["interes_acomulado"] / total_pagado * 100
df_plot["pct_pago_total_pago"] = df_plot["pago_mensual_acomulado"] / total_pagado * 100

fig = go.Figure()

# % Capital acumulado sobre pago total
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_amortizacion_total_pago"],
    mode="lines+markers",
    name="% Capital acumulado",
    customdata=df_plot["cuota"],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "% Capital (vs total pagado): %{y:.2f}%<extra></extra>",
    line=dict(color="seagreen")
))

# % Intereses acumulados sobre pago total
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_interes_total_pago"],
    mode="lines+markers",
    name="% Interés acumulado",
    customdata=df_plot["cuota"],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "% Interés (vs total pagado): %{y:.2f}%<extra></extra>",
    line=dict(color="tomato")
))

# % Total pagado (capital + interés)
fig.add_trace(go.Scatter(
    x=df_plot["periodo"],
    y=df_plot["pct_pago_total_pago"],
    mode="lines+markers",
    name="% Total pagado",
    customdata=df_plot["cuota"],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "% Total acumulado: %{y:.2f}%<extra></extra>",
    line=dict(color="royalblue")
))

# Layout
fig.update_layout(
    title="% de avance del crédito frente al total pagado (capital + intereses)",
    xaxis=dict(title="Periodo"),
    yaxis=dict(
        title="Porcentaje del total pagado (%)",
        range=[0, 105],  # para marcar el 100%
        showgrid=True,
        zeroline=False
    ),
    hovermode="x unified",
    legend=dict(x=0.01, y=0.99, bgcolor="rgba(255,255,255,0.8)")
)

fig.show()

In [13]:
import plotly.graph_objects as go

# Asegurar que periodo sea datetime
df['periodo'] = pd.to_datetime(df['periodo'])

# Omitir la primera fila (cuota 0 con NaN en %)
df_plot = df.iloc[1:]

fig = go.Figure()

# Amortización (eje izquierdo)
fig.add_trace(go.Scatter(
    x=df_plot['periodo'],
    y=df_plot['amortizacion'],
    mode="lines+markers",
    name="Amortización",
    customdata=df_plot['cuota'],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "Amortización: %{y:,.2f}<extra></extra>",
    line=dict(color="seagreen")
))

# Interés (eje izquierdo)
fig.add_trace(go.Scatter(
    x=df_plot['periodo'],
    y=df_plot['interes'],
    mode="lines+markers",
    name="Interés",
    customdata=df_plot['cuota'],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "Interés: %{y:,.2f}<extra></extra>",
    line=dict(color="tomato")
))

# % Amortización sobre pago mensual (eje derecho)
fig.add_trace(go.Scatter(
    x=df_plot['periodo'],
    y=df_plot['pct_amortizacion_pago_mensual']*100,
    mode="lines",
    name="% Amortización / Pago mensual",
    customdata=df_plot['cuota'],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "% Amortización: %{y:.2f}%<extra></extra>",
    line=dict(color="seagreen", dash="dot"),
    yaxis="y2"
))

# % Interés sobre pago mensual (eje derecho)
fig.add_trace(go.Scatter(
    x=df_plot['periodo'],
    y=df_plot['pct_interes_pago_mensual']*100,
    mode="lines",
    name="% Interés / Pago mensual",
    customdata=df_plot['cuota'],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "% Interés: %{y:.2f}%<extra></extra>",
    line=dict(color="tomato", dash="dot"),
    yaxis="y2"
))

# Layout
fig.update_layout(
    title="Amortización e Interés (valores y %)",
    xaxis=dict(title="Periodo"),
    yaxis=dict(
        title="Valores absolutos",
        showgrid=True,
        zeroline=False
    ),
    yaxis2=dict(
        title="Porcentaje",
        overlaying="y",
        side="right",
        showgrid=False
    ),
    hovermode="x unified",
    legend=dict(x=0.01, y=0.99, bgcolor="rgba(255,255,255,0.8)")
)

fig.show()

In [12]:
import plotly.graph_objects as go

df['periodo'] = pd.to_datetime(df['periodo'])

fig = go.Figure()

# Amortización (eje izquierdo)
fig.add_trace(go.Scatter(
    x=df['periodo'],
    y=df['amortizacion'],
    mode="lines+markers",
    name="Amortización",
    customdata=df['cuota'],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "Amortización: %{y:,.2f}<extra></extra>",
    line=dict(color="seagreen")
))

# Interés (eje izquierdo)
fig.add_trace(go.Scatter(
    x=df['periodo'],
    y=df['interes'],
    mode="lines+markers",
    name="Interés",
    customdata=df['cuota'],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "Interés: %{y:,.2f}<extra></extra>",
    line=dict(color="tomato")
))

# % Amortización sobre pago mensual (eje derecho)
fig.add_trace(go.Scatter(
    x=df['periodo'],
    y=df['pct_amortizacion_pago_mensual']*100,
    mode="lines",
    name="% Amortización / Pago mensual",
    customdata=df['cuota'],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "% Amortización: %{y:.2f}%<extra></extra>",
    line=dict(color="seagreen", dash="dot"),
    yaxis="y2"
))

# % Interés sobre pago mensual (eje derecho)
fig.add_trace(go.Scatter(
    x=df['periodo'],
    y=df['pct_interes_pago_mensual']*100,
    mode="lines",
    name="% Interés / Pago mensual",
    customdata=df['cuota'],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "% Interés: %{y:.2f}%<extra></extra>",
    line=dict(color="tomato", dash="dot"),
    yaxis="y2"
))

# Layout
fig.update_layout(
    title="Amortización e Interés (valores y %)",
    xaxis=dict(title="Periodo"),
    yaxis=dict(
        title="Valores absolutos",
        showgrid=True,
        zeroline=False
    ),
    yaxis2=dict(
        title="Porcentaje",
        overlaying="y",
        side="right",
        showgrid=False
    ),
    hovermode="x unified",
    legend=dict(x=0.01, y=0.99, bgcolor="rgba(255,255,255,0.8)")
)

fig.show()

In [11]:
import plotly.graph_objects as go

# Asegurar que periodo es datetime para formatear bonito
df['periodo'] = pd.to_datetime(df['periodo'])

fig = go.Figure()

# Ejemplo con Amortización
fig.add_trace(go.Scatter(
    x=df['periodo'],
    y=df['amortizacion'],
    mode="lines+markers",
    name="Amortización",
    customdata=df['cuota'],  # Pasamos la cuota como dato extra
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +  # fecha en hover
                  "Cuota: %{customdata}<br>" +  # número de cuota
                  "Amortización: %{y:,.2f}<extra></extra>"
))

# Otro ejemplo con Interés
fig.add_trace(go.Scatter(
    x=df['periodo'],
    y=df['interes'],
    mode="lines+markers",
    name="Interés",
    customdata=df['cuota'],
    hovertemplate="Periodo: %{x|%Y-%m}<br>" +
                  "Cuota: %{customdata}<br>" +
                  "Interés: %{y:,.2f}<extra></extra>"
))

fig.update_layout(
    title="Amortización e Interés",
    xaxis_title="Periodo",
    yaxis_title="Valor",
    hovermode="x unified"
)

fig.show()

In [10]:
import plotly.graph_objects as go

# ✅ Opción 1: eje X = periodo, hover = cuota
fig1 = go.Figure()
fig1.add_trace(go.Bar(
    x=df['periodo'], y=df['interes'],
    name="Interés", marker_color="tomato",
    hovertext="Cuota: " + df['cuota'].astype(str)
))
fig1.add_trace(go.Bar(
    x=df['periodo'], y=df['amortizacion'],
    name="Amortización", marker_color="seagreen",
    hovertext="Cuota: " + df['cuota'].astype(str)
))
fig1.update_layout(
    barmode="stack",
    title="Composición del Pago Mensual",
    xaxis_title="Periodo",
    yaxis_title="Monto ($)",
    template="plotly_white"
)

# ✅ Opción 2: eje X = cuota, hover = periodo
fig2 = go.Figure()
fig2.add_trace(go.Scatter(
    x=df['cuota'], y=df['interes_acomulado'],
    mode="lines+markers", name="Interés acumulado",
    line=dict(color="tomato", dash="dot"),
    hovertext=df['periodo'].dt.strftime("%Y-%m")
))
fig2.add_trace(go.Scatter(
    x=df['cuota'], y=df['amortizacion_acomulada'],
    mode="lines+markers", name="Amortización acumulada",
    line=dict(color="seagreen"),
    hovertext=df['periodo'].dt.strftime("%Y-%m")
))

# Totales como asíntotas
fig2.add_hline(y=df['interes_total'].iloc[0], line=dict(color="tomato", dash="dash"),
               annotation_text="Total Interés", annotation_position="top left")
fig2.add_hline(y=df['amortizacion_total'].iloc[0], line=dict(color="seagreen", dash="dash"),
               annotation_text="Total Amortización", annotation_position="top left")
fig2.add_hline(y=df['pago_total_prestamo'].iloc[0], line=dict(color="black", dash="dash"),
               annotation_text="Total Préstamo", annotation_position="top left")

fig2.update_layout(
    title="Evolución Acumulada y Totales",
    xaxis_title="Cuota",
    yaxis_title="Monto ($)",
    template="plotly_white"
)

# ✅ Opción 3: Tasas (%)
fig3 = go.Figure()
fig3.add_trace(go.Scatter(
    x=df['cuota'], y=df['pct_interes_pago_mensual'],
    mode="lines+markers", name="% Interés/Pago mensual",
    line=dict(color="orange"),
    hovertext=df['periodo'].dt.strftime("%Y-%m")
))
fig3.add_trace(go.Scatter(
    x=df['cuota'], y=df['pct_amortizacion_pago_mensual'],
    mode="lines+markers", name="% Amortización/Pago mensual",
    line=dict(color="blue"),
    hovertext=df['periodo'].dt.strftime("%Y-%m")
))
fig3.add_trace(go.Scatter(
    x=df['cuota'], y=df['pct_interes_interes_total'],
    mode="lines+markers", name="% Interés/Total interés",
    line=dict(color="red", dash="dot"),
    hovertext=df['periodo'].dt.strftime("%Y-%m")
))
fig3.add_trace(go.Scatter(
    x=df['cuota'], y=df['pct_interes_acomulado_interes_total'],
    mode="lines+markers", name="% Interés acumulado/Total interés",
    line=dict(color="purple", dash="dot"),
    hovertext=df['periodo'].dt.strftime("%Y-%m")
))

fig3.update_layout(
    title="Evolución de Tasas y Proporciones",
    xaxis_title="Cuota",
    yaxis_title="Proporción (%)",
    yaxis_tickformat=".2%",
    template="plotly_white"
)

# Mostrar
fig1.show()
fig2.show()
fig3.show()

In [6]:
import plotly.graph_objects as go

# Asegúrate de que 'periodo' sea string o datetime para el eje X
df['periodo'] = pd.to_datetime(df['periodo'])

fig = go.Figure()

# --- Gráfico 1: composición del pago mensual ---
fig.add_trace(go.Bar(
    x=df['periodo'],
    y=df['interes'],
    name='Interés',
    marker_color='tomato'
))
fig.add_trace(go.Bar(
    x=df['periodo'],
    y=df['amortizacion'],
    name='Amortización',
    marker_color='seagreen'
))

# --- Gráfico 2: líneas acumuladas ---
fig.add_trace(go.Scatter(
    x=df['periodo'],
    y=df['interes_acomulado'],
    mode='lines+markers',
    name='Interés acumulado',
    line=dict(color='tomato', width=2, dash='dot')
))
fig.add_trace(go.Scatter(
    x=df['periodo'],
    y=df['amortizacion_acomulada'],
    mode='lines+markers',
    name='Amortización acumulada',
    line=dict(color='seagreen', width=2)
))

fig.update_layout(
    barmode='stack',
    title='Evolución del préstamo',
    xaxis_title='Periodo',
    yaxis_title='Monto',
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    hovermode="x unified",
    template="plotly_white"
)

fig.show()

In [7]:
import plotly.graph_objects as go

# Convertir periodo a fecha si no lo está
df['periodo'] = pd.to_datetime(df['periodo'])

fig = go.Figure()

# --- Barras apiladas (pago mensual) ---
fig.add_trace(go.Bar(
    x=df['periodo'],
    y=df['interes'],
    name="Interés (pago mensual)",
    marker_color="tomato",
    hovertemplate="Periodo: %{x}<br>Interés: %{y:,.2f}<extra></extra>",
    yaxis="y1"
))
fig.add_trace(go.Bar(
    x=df['periodo'],
    y=df['amortizacion'],
    name="Amortización (pago mensual)",
    marker_color="seagreen",
    hovertemplate="Periodo: %{x}<br>Amortización: %{y:,.2f}<extra></extra>",
    yaxis="y1"
))

# --- Líneas acumuladas ---
fig.add_trace(go.Scatter(
    x=df['periodo'],
    y=df['interes_acomulado'],
    mode="lines+markers",
    name="Interés acumulado",
    line=dict(color="tomato", dash="dot"),
    yaxis="y1"
))
fig.add_trace(go.Scatter(
    x=df['periodo'],
    y=df['amortizacion_acomulada'],
    mode="lines+markers",
    name="Amortización acumulada",
    line=dict(color="seagreen"),
    yaxis="y1"
))

# --- Líneas de porcentajes ---
fig.add_trace(go.Scatter(
    x=df['periodo'],
    y=df['pct_interes_pago_mensual'],
    mode="lines",
    name="% Interés / Pago mensual",
    line=dict(color="orange", width=2),
    yaxis="y2"
))
fig.add_trace(go.Scatter(
    x=df['periodo'],
    y=df['pct_amortizacion_pago_mensual'],
    mode="lines",
    name="% Amortización / Pago mensual",
    line=dict(color="blue", width=2),
    yaxis="y2"
))

# --- Layout ---
fig.update_layout(
    title="Evolución del préstamo: pagos, acumulados y porcentajes",
    barmode="stack",
    xaxis=dict(title="Periodo"),
    yaxis=dict(
        title="Montos ($)",
        side="left",
        showgrid=True
    ),
    yaxis2=dict(
        title="Porcentaje del pago mensual",
        overlaying="y",
        side="right",
        tickformat=".0%",
        showgrid=False
    ),
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    hovermode="x unified",
    template="plotly_white",
    height=600
)

fig.show()

In [8]:
import plotly.graph_objects as go

# Asegurar fechas en el eje X
df['periodo'] = pd.to_datetime(df['periodo'])

fig = go.Figure()

# --- Barras apiladas: pago mensual ---
fig.add_trace(go.Bar(
    x=df['periodo'], y=df['interes'],
    name="Interés (pago mensual)", marker_color="tomato",
    yaxis="y1"
))
fig.add_trace(go.Bar(
    x=df['periodo'], y=df['amortizacion'],
    name="Amortización (pago mensual)", marker_color="seagreen",
    yaxis="y1"
))

# --- Líneas acumuladas ---
fig.add_trace(go.Scatter(
    x=df['periodo'], y=df['interes_acomulado'],
    mode="lines+markers", name="Interés acumulado",
    line=dict(color="tomato", dash="dot"), yaxis="y1"
))
fig.add_trace(go.Scatter(
    x=df['periodo'], y=df['amortizacion_acomulada'],
    mode="lines+markers", name="Amortización acumulada",
    line=dict(color="seagreen"), yaxis="y1"
))

# --- Líneas horizontales de totales ---
fig.add_hline(y=df['interes_total'].iloc[0],
              line=dict(color="tomato", dash="dash"),
              annotation_text="Total Interés", annotation_position="top left")
fig.add_hline(y=df['amortizacion_total'].iloc[0],
              line=dict(color="seagreen", dash="dash"),
              annotation_text="Total Amortización", annotation_position="top left")
fig.add_hline(y=df['pago_total_prestamo'].iloc[0],
              line=dict(color="black", dash="dash"),
              annotation_text="Total Préstamo", annotation_position="top left")

# --- Tasas (eje derecho) ---
fig.add_trace(go.Scatter(
    x=df['periodo'], y=df['pct_interes_pago_mensual'],
    mode="lines", name="% Interés/Pago", line=dict(color="orange", width=2),
    yaxis="y2"
))
fig.add_trace(go.Scatter(
    x=df['periodo'], y=df['pct_amortizacion_pago_mensual'],
    mode="lines", name="% Amortización/Pago", line=dict(color="blue", width=2),
    yaxis="y2"
))
fig.add_trace(go.Scatter(
    x=df['periodo'], y=df['pct_interes_interes_total'],
    mode="lines", name="% Interés/Total Interés", line=dict(color="red", width=2, dash="dot"),
    yaxis="y2"
))
fig.add_trace(go.Scatter(
    x=df['periodo'], y=df['pct_interes_acomulado_interes_total'],
    mode="lines", name="% Interés Acumulado/Total", line=dict(color="purple", width=2, dash="dot"),
    yaxis="y2"
))

# --- Layout ---
fig.update_layout(
    title="Evolución completa del préstamo",
    barmode="stack",
    xaxis=dict(title="Periodo"),
    yaxis=dict(
        title="Montos ($)",
        side="left",
        showgrid=True
    ),
    yaxis2=dict(
        title="Proporciones (%)",
        overlaying="y",
        side="right",
        tickformat=".2%",
        showgrid=False
    ),
    legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
    hovermode="x unified",
    template="plotly_white",
    height=700
)

fig.show()

In [9]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# Asegurar fechas
df['periodo'] = pd.to_datetime(df['periodo'])

# --- 1. Composición del pago mensual ---
fig1 = go.Figure()
fig1.add_trace(go.Bar(x=df['periodo'], y=df['interes'],
                      name="Interés", marker_color="tomato"))
fig1.add_trace(go.Bar(x=df['periodo'], y=df['amortizacion'],
                      name="Amortización", marker_color="seagreen"))
fig1.update_layout(
    barmode="stack",
    title="Composición del Pago Mensual",
    xaxis_title="Periodo",
    yaxis_title="Monto ($)",
    template="plotly_white"
)

# --- 2. Acumulados con totales ---
fig2 = go.Figure()
fig2.add_trace(go.Scatter(x=df['periodo'], y=df['interes_acomulado'],
                          mode="lines+markers", name="Interés acumulado",
                          line=dict(color="tomato", dash="dot")))
fig2.add_trace(go.Scatter(x=df['periodo'], y=df['amortizacion_acomulada'],
                          mode="lines+markers", name="Amortización acumulada",
                          line=dict(color="seagreen")))

# Líneas horizontales de totales
fig2.add_hline(y=df['interes_total'].iloc[0], line=dict(color="tomato", dash="dash"),
               annotation_text="Total Interés", annotation_position="top left")
fig2.add_hline(y=df['amortizacion_total'].iloc[0], line=dict(color="seagreen", dash="dash"),
               annotation_text="Total Amortización", annotation_position="top left")
fig2.add_hline(y=df['pago_total_prestamo'].iloc[0], line=dict(color="black", dash="dash"),
               annotation_text="Total Préstamo", annotation_position="top left")

fig2.update_layout(
    title="Evolución Acumulada y Totales",
    xaxis_title="Periodo",
    yaxis_title="Monto ($)",
    template="plotly_white"
)

# --- 3. Tasas (% proporciones) ---
fig3 = go.Figure()
fig3.add_trace(go.Scatter(x=df['periodo'], y=df['pct_interes_pago_mensual'],
                          mode="lines+markers", name="% Interés/Pago mensual",
                          line=dict(color="orange")))
fig3.add_trace(go.Scatter(x=df['periodo'], y=df['pct_amortizacion_pago_mensual'],
                          mode="lines+markers", name="% Amortización/Pago mensual",
                          line=dict(color="blue")))
fig3.add_trace(go.Scatter(x=df['periodo'], y=df['pct_interes_interes_total'],
                          mode="lines+markers", name="% Interés/Total interés",
                          line=dict(color="red", dash="dot")))
fig3.add_trace(go.Scatter(x=df['periodo'], y=df['pct_interes_acomulado_interes_total'],
                          mode="lines+markers", name="% Interés acumulado/Total interés",
                          line=dict(color="purple", dash="dot")))

fig3.update_layout(
    title="Evolución de Tasas y Proporciones",
    xaxis_title="Periodo",
    yaxis_title="Proporción (%)",
    yaxis_tickformat=".2%",
    template="plotly_white"
)

# Mostrar
fig1.show()
fig2.show()
fig3.show()

In [5]:
import plotly.graph_objects as go

# ✅ Opción 1: eje X = periodo, hover = cuota
fig1 = go.Figure()
fig1.add_trace(go.Bar(
    x=df['periodo'], y=df['interes'],
    name="Interés", marker_color="tomato",
    hovertext="Cuota: " + df['cuota'].astype(str)
))
fig1.add_trace(go.Bar(
    x=df['periodo'], y=df['amortizacion'],
    name="Amortización", marker_color="seagreen",
    hovertext="Cuota: " + df['cuota'].astype(str)
))
fig1.update_layout(
    barmode="stack",
    title="Composición del Pago Mensual",
    xaxis_title="Periodo",
    yaxis_title="Monto ($)",
    template="plotly_white"
)

# ✅ Opción 2: eje X = cuota, hover = periodo
fig2 = go.Figure()
fig2.add_trace(go.Scatter(
    x=df['cuota'], y=df['interes_acomulado'],
    mode="lines+markers", name="Interés acumulado",
    line=dict(color="tomato", dash="dot"),
    hovertext=df['periodo'].dt.strftime("%Y-%m")
))
fig2.add_trace(go.Scatter(
    x=df['cuota'], y=df['amortizacion_acomulada'],
    mode="lines+markers", name="Amortización acumulada",
    line=dict(color="seagreen"),
    hovertext=df['periodo'].dt.strftime("%Y-%m")
))

# Totales como asíntotas
fig2.add_hline(y=df['interes_total'].iloc[0], line=dict(color="tomato", dash="dash"),
               annotation_text="Total Interés", annotation_position="top left")
fig2.add_hline(y=df['amortizacion_total'].iloc[0], line=dict(color="seagreen", dash="dash"),
               annotation_text="Total Amortización", annotation_position="top left")
fig2.add_hline(y=df['pago_total_prestamo'].iloc[0], line=dict(color="black", dash="dash"),
               annotation_text="Total Préstamo", annotation_position="top left")

fig2.update_layout(
    title="Evolución Acumulada y Totales",
    xaxis_title="Cuota",
    yaxis_title="Monto ($)",
    template="plotly_white"
)

# ✅ Opción 3: Tasas (%)
fig3 = go.Figure()
fig3.add_trace(go.Scatter(
    x=df['cuota'], y=df['pct_interes_pago_mensual'],
    mode="lines+markers", name="% Interés/Pago mensual",
    line=dict(color="orange"),
    hovertext=df['periodo'].dt.strftime("%Y-%m")
))
fig3.add_trace(go.Scatter(
    x=df['cuota'], y=df['pct_amortizacion_pago_mensual'],
    mode="lines+markers", name="% Amortización/Pago mensual",
    line=dict(color="blue"),
    hovertext=df['periodo'].dt.strftime("%Y-%m")
))
fig3.add_trace(go.Scatter(
    x=df['cuota'], y=df['pct_interes_interes_total'],
    mode="lines+markers", name="% Interés/Total interés",
    line=dict(color="red", dash="dot"),
    hovertext=df['periodo'].dt.strftime("%Y-%m")
))
fig3.add_trace(go.Scatter(
    x=df['cuota'], y=df['pct_interes_acomulado_interes_total'],
    mode="lines+markers", name="% Interés acumulado/Total interés",
    line=dict(color="purple", dash="dot"),
    hovertext=df['periodo'].dt.strftime("%Y-%m")
))

fig3.update_layout(
    title="Evolución de Tasas y Proporciones",
    xaxis_title="Cuota",
    yaxis_title="Proporción (%)",
    yaxis_tickformat=".2%",
    template="plotly_white"
)

# Mostrar
fig1.show()
fig2.show()
fig3.show()

KeyError: 'cuota'

In [39]:
df_sample = df[0:13]
df_sample

    periodo  amortizacion    interes  pago_mensual         saldo
0   2021-11          0.00       0.00          0.00 90,000,000.00
1   2021-12    791,952.54 627,008.06  1,418,960.61 89,208,047.46
2   2022-01    797,469.88 621,490.72  1,418,960.61 88,410,577.57
3   2022-02    803,025.66 615,934.94  1,418,960.61 87,607,551.91
4   2022-03    808,620.15 610,340.46  1,418,960.61 86,798,931.76
5   2022-04    814,253.61 604,707.00  1,418,960.61 85,984,678.16
6   2022-05    819,926.31 599,034.29  1,418,960.61 85,164,751.85
7   2022-06    825,638.54 593,322.07  1,418,960.61 84,339,113.31
8   2022-07    831,390.56 587,570.05  1,418,960.61 83,507,722.75
9   2022-08    837,182.66 581,777.95  1,418,960.61 82,670,540.09
10  2022-09    843,015.10 575,945.50  1,418,960.61 81,827,524.98
11  2022-10    848,888.19 570,072.42  1,418,960.61 80,978,636.80
12  2022-11    854,802.18 564,158.42  1,418,960.61 80,123,834.62

In [50]:
90_000_000*0.08688

7819200.0

In [49]:
((627008.06*12)/90_000_000)*100

8.360107466666667

In [45]:
df_sample.pago_mensual.sum()

np.float64(17027527.319999997)

In [44]:
df_sample.amortizacion.sum()

np.float64(9876165.379999999)

In [40]:
df_sample.interes.sum()

np.float64(7151361.88)

In [46]:
df_sample.interes.sum()/df_sample.pago_mensual.sum()

np.float64(0.41998827813362166)

In [43]:
round(df_sample.interes.sum()/90_000_000,6)*100

np.float64(7.946000000000001)

In [9]:
df.amortizacion.sum()

np.float64(90000000.0)

In [7]:
df.interes.sum()

np.float64(29192690.95)

# 02. Prestamo actual

In [17]:
df_primera_parte = df[0:25]
df_primera_parte

    periodo  amortizacion    interes  pago_mensual         saldo
0   2021-11          0.00       0.00          0.00 90,000,000.00
1   2021-12    791,952.54 627,008.06  1,418,960.61 89,208,047.46
2   2022-01    797,469.88 621,490.72  1,418,960.61 88,410,577.57
3   2022-02    803,025.66 615,934.94  1,418,960.61 87,607,551.91
4   2022-03    808,620.15 610,340.46  1,418,960.61 86,798,931.76
5   2022-04    814,253.61 604,707.00  1,418,960.61 85,984,678.16
6   2022-05    819,926.31 599,034.29  1,418,960.61 85,164,751.85
7   2022-06    825,638.54 593,322.07  1,418,960.61 84,339,113.31
8   2022-07    831,390.56 587,570.05  1,418,960.61 83,507,722.75
9   2022-08    837,182.66 581,777.95  1,418,960.61 82,670,540.09
10  2022-09    843,015.10 575,945.50  1,418,960.61 81,827,524.98
11  2022-10    848,888.19 570,072.42  1,418,960.61 80,978,636.80
12  2022-11    854,802.18 564,158.42  1,418,960.61 80,123,834.62
13  2022-12    860,757.38 558,203.23  1,418,960.61 79,263,077.24
14  2023-01    866,754.07 552,206.54  1,418,960.61 78,396,323.17
15  2023-02    872,792.53 546,168.08  1,418,960.61 77,523,530.64
16  2023-03    878,873.06 540,087.54  1,418,960.61 76,644,657.57
17  2023-04    884,995.96 533,964.65  1,418,960.61 75,759,661.61
18  2023-05    891,161.51 527,799.10  1,418,960.61 74,868,500.10
19  2023-06    897,370.02 521,590.59  1,418,960.61 73,971,130.09
20  2023-07    903,621.77 515,338.83  1,418,960.61 73,067,508.31
21  2023-08    909,917.09 509,043.52  1,418,960.61 72,157,591.23
22  2023-09    916,256.26 502,704.35  1,418,960.61 71,241,334.97
23  2023-10    922,639.59 496,321.02  1,418,960.61 70,318,695.38
24  2023-11    929,067.40 489,893.21  1,418,960.61 69,389,627.99

In [19]:
df_02 = tabla_mensual_amortizacion_francesa(
    capital_inicial=39_256_073.95,
    tasa=0.08688,
    periodos_n = 31,
    periodos_temporalidad = 'mensual',
    tasa_temporalidad='anual',
    tasa_tipo='efectiva'
)

fecha_inicio = '2025-06-01'

# Crear rango de fechas mensuales
fechas = pd.date_range(start=fecha_inicio, periods=len(df), freq='MS')  # 'MS' = Month Start

# Crear nueva columna con formato 'YYYY-MM'
df_02['periodo'] = fechas.strftime('%Y-%m')
df_02

x = 2 39256073.95

    periodo  amortizacion    interes  pago_mensual         saldo
0   2025-06          0.00       0.00          0.00 39,256,073.95
1   2025-07  1,138,888.43 273,487.50  1,412,375.93 38,117,185.52
2   2025-08  1,146,822.79 265,553.14  1,412,375.93 36,970,362.73
3   2025-09  1,154,812.42 257,563.51  1,412,375.93 35,815,550.31
4   2025-10  1,162,857.72 249,518.21  1,412,375.93 34,652,692.58
5   2025-11  1,170,959.07 241,416.86  1,412,375.93 33,481,733.52
6   2025-12  1,179,116.85 233,259.08  1,412,375.93 32,302,616.66
7   2026-01  1,187,331.47 225,044.46  1,412,375.93 31,115,285.19
8   2026-02  1,195,603.32 216,772.61  1,412,375.93 29,919,681.87
9   2026-03  1,203,932.80 208,443.13  1,412,375.93 28,715,749.07
10  2026-04  1,212,320.31 200,055.62  1,412,375.93 27,503,428.76
11  2026-05  1,220,766.25 191,609.68  1,412,375.93 26,282,662.52
12  2026-06  1,229,271.03 183,104.90  1,412,375.93 25,053,391.49
13  2026-07  1,237,835.06 174,540.87  1,412,375.93 23,815,556.43
14  2026-08  1,246,458.75 165,917.18  1,412,375.93 22,569,097.68
15  2026-09  1,255,142.53 157,233.40  1,412,375.93 21,313,955.15
16  2026-10  1,263,886.80 148,489.13  1,412,375.93 20,050,068.35
17  2026-11  1,272,691.99 139,683.94  1,412,375.93 18,777,376.36
18  2026-12  1,281,558.53 130,817.40  1,412,375.93 17,495,817.84
19  2027-01  1,290,486.83 121,889.10  1,412,375.93 16,205,331.01
20  2027-02  1,299,477.34 112,898.59  1,412,375.93 14,905,853.67
21  2027-03  1,308,530.48 103,845.45  1,412,375.93 13,597,323.19
22  2027-04  1,317,646.69  94,729.24  1,412,375.93 12,279,676.49
23  2027-05  1,326,826.42  85,549.51  1,412,375.93 10,952,850.07
24  2027-06  1,336,070.09  76,305.84  1,412,375.93  9,616,779.98
25  2027-07  1,345,378.17  66,997.76  1,412,375.93  8,271,401.81
26  2027-08  1,354,751.09  57,624.84  1,412,375.93  6,916,650.72
27  2027-09  1,364,189.31  48,186.62  1,412,375.93  5,552,461.41
28  2027-10  1,373,693.28  38,682.65  1,412,375.93  4,178,768.13
29  2027-11  1,383,263.47  29,112.46  1,412,375.93  2,795,504.66
30  2027-12  1,392,900.33  19,475.60  1,412,375.93  1,402,604.33
31  2028-01  1,402,604.33   9,771.60  1,412,375.93          0.00

In [20]:
1145154.86+265576.14+6913.00+29674.00

1447318.0

In [24]:
df_2025_09_to_end = df_02[3:]
df_2025_09_to_end

    periodo  amortizacion    interes  pago_mensual         saldo
3   2025-09  1,154,812.42 257,563.51  1,412,375.93 35,815,550.31
4   2025-10  1,162,857.72 249,518.21  1,412,375.93 34,652,692.58
5   2025-11  1,170,959.07 241,416.86  1,412,375.93 33,481,733.52
6   2025-12  1,179,116.85 233,259.08  1,412,375.93 32,302,616.66
7   2026-01  1,187,331.47 225,044.46  1,412,375.93 31,115,285.19
8   2026-02  1,195,603.32 216,772.61  1,412,375.93 29,919,681.87
9   2026-03  1,203,932.80 208,443.13  1,412,375.93 28,715,749.07
10  2026-04  1,212,320.31 200,055.62  1,412,375.93 27,503,428.76
11  2026-05  1,220,766.25 191,609.68  1,412,375.93 26,282,662.52
12  2026-06  1,229,271.03 183,104.90  1,412,375.93 25,053,391.49
13  2026-07  1,237,835.06 174,540.87  1,412,375.93 23,815,556.43
14  2026-08  1,246,458.75 165,917.18  1,412,375.93 22,569,097.68
15  2026-09  1,255,142.53 157,233.40  1,412,375.93 21,313,955.15
16  2026-10  1,263,886.80 148,489.13  1,412,375.93 20,050,068.35
17  2026-11  1,272,691.99 139,683.94  1,412,375.93 18,777,376.36
18  2026-12  1,281,558.53 130,817.40  1,412,375.93 17,495,817.84
19  2027-01  1,290,486.83 121,889.10  1,412,375.93 16,205,331.01
20  2027-02  1,299,477.34 112,898.59  1,412,375.93 14,905,853.67
21  2027-03  1,308,530.48 103,845.45  1,412,375.93 13,597,323.19
22  2027-04  1,317,646.69  94,729.24  1,412,375.93 12,279,676.49
23  2027-05  1,326,826.42  85,549.51  1,412,375.93 10,952,850.07
24  2027-06  1,336,070.09  76,305.84  1,412,375.93  9,616,779.98
25  2027-07  1,345,378.17  66,997.76  1,412,375.93  8,271,401.81
26  2027-08  1,354,751.09  57,624.84  1,412,375.93  6,916,650.72
27  2027-09  1,364,189.31  48,186.62  1,412,375.93  5,552,461.41
28  2027-10  1,373,693.28  38,682.65  1,412,375.93  4,178,768.13
29  2027-11  1,383,263.47  29,112.46  1,412,375.93  2,795,504.66
30  2027-12  1,392,900.33  19,475.60  1,412,375.93  1,402,604.33
31  2028-01  1,402,604.33   9,771.60  1,412,375.93          0.00

In [25]:
df_2025_09_to_end.amortizacion.sum()

np.float64(36970362.73)

In [26]:
df_2025_09_to_end.interes.sum()

np.float64(3988539.2399999998)

In [27]:
df_2025_09_to_end.pago_mensual.sum()

np.float64(40958901.97)

In [32]:
df_2025_09_to_end.interes.sum()/df_2025_09_to_end.pago_mensual.sum()

np.float64(0.09737905676576417)

In [31]:
df_2025_09_to_end.interes.sum()/df_2025_09_to_end.amortizacion.sum()

np.float64(0.10788477432934292)

In [30]:
df_2025_09_to_end.amortizacion.sum()/df_2025_09_to_end.pago_mensual.sum()

np.float64(0.9026209432342358)